/** Static, local owner-review report. No app assets or live site are changed. */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve, join } from 'node:path'
import { fileURLToPath } from 'node:url'
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..')
const out=join(root,'docs/audit/2026-10-04-registration-candidate')
const json=file=>JSON.parse(readFileSync(join(out,file),'utf8'))
const m=json('measurements.json'),landmarks=json('mri-landmarks.json')
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')
const appUrl=process.argv[2]??'http://127.0.0.1:5193/neuroaxis-atlas/'
if (!/^https?:\/\//.test(appUrl)) throw new Error('Expected an HTTP app URL')
for (const f of m.figures) if (!/^[a-z0-9-]+\.png$/.test(f.file)) throw new Error('Unexpected figure filename')
const rows=landmarks.observations.map(r=>`<tr class="${r.candidateResidualAu>r.baselineResidualAu?'worse':'better'}"><td>${esc(r.id.replaceAll('-',' '))}</td><td>${esc(r.region)}</td><td>${r.split==='fit'?'Fitting':'Reserved check'}</td><td>${r.baselineResidualAu.toFixed(2)}</td><td>${r.candidateResidualAu.toFixed(2)}</td><td>${r.uncertaintyAu}</td></tr>`).join('')
const options=m.figures.map((f,i)=>`<option value="${i}">${esc(f.title)}</option>`).join('')
const reserved=landmarks.observations.filter(r=>r.split==='holdout')
const mean=key=>(reserved.reduce((s,r)=>s+r[key],0)/reserved.length).toFixed(2)
const figuresJson=JSON.stringify(m.figures).replaceAll('<','\\u003c')
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NeuroAxis · MRI and CT registration candidate review</title><style>
:root{color-scheme:dark;font:16px/1.5 system-ui,sans-serif;color:#e1eaf4;background:#0c1421}*{box-sizing:border-box}body{margin:0}main{max-width:1440px;margin:auto;padding:24px}h1{font-size:clamp(24px,3vw,36px);margin:0 0 8px}h2{font-size:21px;margin:24px 0 10px}p{margin:8px 0}a{color:#59cdf5}a:focus-visible,select:focus-visible,button:focus-visible{outline:3px solid #64d7fb;outline-offset:3px}.top{display:flex;align-items:start;justify-content:space-between;gap:18px;flex-wrap:wrap}.tag{color:#88dbf8;font-size:13px;letter-spacing:.08em}.action{display:inline-block;padding:10px 16px;border:1px solid #35bcef;border-radius:8px;text-decoration:none;background:#153749}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:20px 0}.card,.note{padding:14px 16px;background:#121f31;border:1px solid #2a3d56;border-radius:10px}.card strong{display:block;font-size:24px;color:#66d4f6}.card small{color:#a9bdd0}.note{border-left:4px solid #dfaf58;margin:12px 0}.toolbar{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin:14px 0}select,button{font:inherit;color:inherit;background:#162638;border:1px solid #48627e;border-radius:6px;padding:6px 10px}select{max-width:100%}figure{margin:0;border:1px solid #2a3d56;border-radius:10px;background:#101b2a;overflow:hidden}figure img{width:100%;height:auto;display:block}figcaption{padding:10px 14px;color:#a9bdd0;font-size:14px}.table-scroll{overflow:auto;border:1px solid #2a3d56;border-radius:8px}table{width:100%;border-collapse:collapse;font-size:14px}th,td{padding:9px 12px;text-align:left;border-bottom:1px solid #23354b}th{background:#172638;white-space:nowrap}.worse td:nth-child(5){color:#ffad8e}.better td:nth-child(5){color:#9cddb7}.muted{color:#a5b9ce;font-size:14px}.links{display:flex;gap:18px;flex-wrap:wrap;margin:14px 0}footer{margin-top:26px;border-top:1px solid #2a3d56;padding:18px 0;color:#a5b9ce;font-size:13px}@media(max-width:800px){main{padding:16px}.cards{grid-template-columns:repeat(2,1fr)}.card strong{font-size:21px}}@media(max-width:420px){.cards{grid-template-columns:1fr}}
</style></head><body><main><header class="top"><div><div class="tag">CANDIDATE · OWNER REVIEW PENDING · 4 OCTOBER 2026</div><h1>NeuroAxis MRI and CT registration review</h1><p>MRI and provisional CT are available in the local candidate. The public deployment is unchanged.</p></div><a class="action" href="${esc(appUrl)}" target="_blank" rel="noreferrer">Open candidate app ↗</a></header>
<div class="cards"><div class="card"><strong>97 × 138 × 122</strong><small>Expanded MRI station grid</small></div><div class="card"><strong>979,371 exact</strong><small>Old samples preserved in the crop-only check</small></div><div class="card"><strong>206,241 exact</strong><small>Independent source checks per modality</small></div><div class="card"><strong>138 unchanged</strong><small>Original GLB meshes; no forced reshaping</small></div></div>
<div class="note"><strong>Better overall placement, with remaining regional differences.</strong><p>The cerebellum is still poorly matched: inferior and posterior observations differ by 14.15 and 24.00 au. The callosal splenium worsens to 8.14 au. Cortical folds and ventricular horns are schematic. These overlays provide approximate orientation, not precise tissue boundaries or clinical measurements.</p></div>
<h2>Before / after figures</h2><p class="muted">The first three comparisons show the published crop, a crop-only extension, and the candidate affine. CT panels show the provisional corrected grid now available in the local candidate.</p><div class="toolbar"><label for="figure-picker">Figure</label><select id="figure-picker">${options}</select><a id="full-figure" href="${esc(m.figures[0].file)}" target="_blank" rel="noreferrer">Open full resolution ↗</a></div><figure><img id="figure" src="${esc(m.figures[0].file)}" alt="${esc(m.figures[0].title)}"><figcaption id="figure-caption">${esc(m.figures[0].title)}</figcaption></figure>
<h2>All MRI observations and tradeoffs</h2><p>Ten observations were used for fitting; seven were reserved. Mean reserved mismatch: <strong>${mean('baselineResidualAu')} → ${mean('candidateResidualAu')} au</strong>. This combines component observations and is not clinical target-registration error or a percentage anatomical accuracy.</p><p class="muted">Manual visual observations from one review; no independent expert annotations. Uncertainty is the fitting scale assigned to the observation, not a confidence interval. Orange values got worse. One au is approximately 1.2 mm.</p><div class="table-scroll"><table><thead><tr><th>Observation</th><th>Region</th><th>Role</th><th>Before, au</th><th>Candidate, au</th><th>Pick uncertainty, au</th></tr></thead><tbody>${rows}</tbody></table></div>
<h2>Coverage and interpretation</h2><p>Previously, 23.28% / 23.64% of cortical mesh vertices lay outside the baked image grid. The candidate grid covers all cortical vertices. This is a field-of-view check: it does not establish that each vertex is on the actual cortex. The acquisition field contains scalp, CSF and background too. Missing image coverage is transparent; simulated anatomy can remain visible there.</p><p>CT now uses the correct anterior sign and actual slice positions. The old mean-spacing assumption produced a 1.457792 mm source-position error. Corrected source sampling is reproducible, but the coarse CT-to-atlas placement remains provisional because artifacts limit fine correspondence.</p>
<div class="links"><a href="README.md">Full methods and limitations</a><a href="measurements.json">Independent measurements</a><a href="mri-landmarks.json">MRI observation ledger</a><a href="ct-landmarks.json">Provisional CT ledger</a><a href="verification.md">Verification record</a></div>
<footer><p>MRI: <a href="https://openneuro.org/datasets/ds007313/versions/1.0.0">OpenNeuro ds007313 v1.0.0</a> (CC0). CT: Courtesy of the U.S. National Library of Medicine; <a href="https://www.nlm.nih.gov/databases/download/terms_and_conditions.html">NLM terms</a>. Different subjects; no paired MRI/CT validation is claimed. No textbook images are reproduced.</p><p>© 2026 Webster Wang. All rights reserved for original NeuroAxis work; third-party source terms apply. <a href="mailto:websterwangai@gmail.com">websterwangai@gmail.com</a></p></footer>
<script>const figures=${figuresJson};document.querySelector('#figure-picker').addEventListener('change',e=>{const f=figures[Number(e.target.value)];const img=document.querySelector('#figure');img.src=f.file;img.alt=f.title;document.querySelector('#figure-caption').textContent=f.title;document.querySelector('#full-figure').href=f.file});</script></main></body></html>`
writeFileSync(join(out,'index.html'),html)
console.log(`Review report: ${join(out,'index.html')}`)
