/**
 * budget-report.mjs — re-derive the v7 hard budgets from the COMMITTED
 * artifacts alone (plan §4.3 item 2, gate table row 9).
 *
 * WHY THIS FILE EXISTS
 * The three budget caps in this run are binding constraints
 * (`docs/TELENCEPHALON_PLAN.md` §4 / `REALISM_PLAN §2.7 AMENDMENT A`):
 *
 *     rendered triangles  ≤ 800,000
 *     committed GLB       ≤ 14 MiB
 *     imaging payload     ≤ 10 MiB
 *
 * `node scripts/build-anatomy-geometry.mjs --manifest` re-bakes and re-verifies
 * them, but it needs the untracked `assets-src/` sources to be meaningful work
 * — and an evidence command must never require an external precondition. This
 * gate reads only what is COMMITTED (`src/assets/**` + the manifest the build
 * wrote) and answers the same three questions with the same arithmetic:
 *
 *   • rendered tris  = Σ `parts[].triCount` — what the scene actually draws
 *                      (the 106 manifest parts, not the source meshes);
 *   • GLB payload    = Σ stat(part.file) — the committed payload the browser
 *                      downloads, plus the whole committed asset tree as a
 *                      second, stricter reading;
 *   • imaging        = Σ stat(every file under src/assets/imaging).
 *
 * It is deliberately independent of the build script: if a future re-bake
 * changed the manifest without changing the assets (or vice versa), the two
 * gates disagree and both say so.
 *
 * Tier 1: pure Node, no network, no browser, no external precondition.
 * Run:  node scripts/verify/budget-report.mjs     (exit 0 = every cap respected)
 */
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs'
import { resolve } from 'node:path'

const ROOT = resolve('.')
const MIB = 1024 * 1024

/** The caps this gate enforces (plan §4 tables; not read from a manifest). */
const CAPS = Object.freeze({
  tris: 800000,
  glbMiB: 14,
  imagingMiB: 10,
})

const checks = []
const infos = []
const ok = (message) => checks.push(`  ✓ ${message}`)
const bad = (message) => checks.push(`  ✗ ${message}`)
const info = (message) => infos.push(`  ·  ${message}`)

const readJson = (relative) => JSON.parse(readFileSync(resolve(ROOT, relative), 'utf8'))
const num = (value) => value.toLocaleString('en-US')
const mib = (bytes) => bytes / MIB
const home = (bytes) =>
  bytes < MIB ? `${(bytes / 1024).toFixed(1)} KiB` : `${mib(bytes).toFixed(2)} MiB`

/* ------------------------------------------------------ the committed tree */

/** Sum every file under a directory tree (recursive), or null when absent. */
function dirBytes(relative) {
  const root = resolve(ROOT, relative)
  if (!existsSync(root)) return null
  let total = 0
  let files = 0
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const full = resolve(root, entry.name)
    if (entry.isDirectory()) {
      const nested = dirBytes(`${relative}/${entry.name}`)
      total += nested.bytes
      files += nested.files
    } else {
      total += statSync(full).size
      files += 1
    }
  }
  return { bytes: total, files }
}

const MANIFEST_PATH = 'src/assets/anatomy/anatomy-manifest.json'

if (!existsSync(resolve(ROOT, MANIFEST_PATH))) {
  console.log('\n================ NeuroAxis budget report (Tier 1) ================')
  console.log(`  ✗ ${MANIFEST_PATH} is missing — the anatomy budget cannot be re-derived`)
  console.log('\n1 passed · 1 failed\n')
  process.exit(1)
}

const manifest = readJson(MANIFEST_PATH)
const parts = Array.isArray(manifest.parts) ? manifest.parts : []

/* --------------------------------------------------------------- triangles */

const tris = parts.reduce((sum, part) => sum + (part.triCount ?? 0), 0)
const largest = parts.reduce(
  (best, part) => ((part.triCount ?? 0) > (best?.triCount ?? -1) ? part : best),
  null,
)

/* --------------------------------------------------------------- GLB bytes */

let glbBytes = 0
const missingFiles = []
for (const part of parts) {
  const full = resolve(ROOT, 'src/assets/anatomy', part.file ?? '')
  if (part.file !== undefined && existsSync(full)) glbBytes += statSync(full).size
  else missingFiles.push(part.slug ?? part.file ?? '(unnamed)')
}

/* ------------------------------------------------- the whole committed tree */

const anatomyTree = dirBytes('src/assets/anatomy')
const imagingTree = dirBytes('src/assets/imaging')

/* ------------------------------------------------------------------ report */

console.log('\n================ NeuroAxis budget report (Tier 1) ================')
console.log('  source: the COMMITTED manifest + the COMMITTED asset tree (no re-bake, no precondition)')
console.log(
  `  manifest: ${MANIFEST_PATH} · ${parts.length} part(s) · generated by ${String(manifest.generatedBy ?? '?')}`,
)

const kinds = new Map()
for (const part of parts) {
  const kind = String(part.kind ?? 'unknown')
  const row = kinds.get(kind) ?? { count: 0, tris: 0 }
  row.count += 1
  row.tris += part.triCount ?? 0
  kinds.set(kind, row)
}
info(
  `part mix: ${[...kinds.entries()]
    .map(([kind, row]) => `${kind} ${row.count} (${num(row.tris)} tris)`)
    .join(' · ')}`,
)

console.log('\n── (1) rendered triangles ' + '─'.repeat(52))
info(
  `Σ parts[].triCount = ${num(tris)} triangles` +
    (largest === null ? '' : ` · largest ${largest.slug} ${num(largest.triCount ?? 0)}`),
)
tris <= CAPS.tris
  ? ok(`rendered triangles ${num(tris)} ≤ ${num(CAPS.tris)}`)
  : bad(`rendered triangles ${num(tris)} EXCEED the ${num(CAPS.tris)} cap by ${num(tris - CAPS.tris)}`)

console.log('\n── (2) committed anatomy GLB ' + '─'.repeat(50))
info(`Σ stat(part.file) = ${num(glbBytes)} B (${mib(glbBytes).toFixed(2)} MiB)`)
mib(glbBytes) <= CAPS.glbMiB
  ? ok(
      `committed GLB payload ${mib(glbBytes).toFixed(2)} MiB ≤ ${CAPS.glbMiB} MiB ` +
        `(headroom ${(CAPS.glbMiB - mib(glbBytes)).toFixed(2)} MiB)`,
    )
  : bad(`committed GLB payload ${mib(glbBytes).toFixed(2)} MiB EXCEEDS the ${CAPS.glbMiB} MiB cap`)
missingFiles.length === 0
  ? ok(`every one of the ${parts.length} manifest part(s) has its committed GLB on disk`)
  : bad(`${missingFiles.length} manifest part(s) have no GLB file: ${missingFiles.slice(0, 5).join(', ')}`)
if (anatomyTree !== null) {
  // Stricter, second reading: EVERY committed byte under the asset directory
  // (GLBs + the manifest + any report). If this passes, the cap holds however
  // the payload is measured.
  info(`whole committed asset tree: ${home(anatomyTree.bytes)} in ${anatomyTree.files} file(s)`)
  mib(anatomyTree.bytes) <= CAPS.glbMiB
    ? ok(
        `the whole src/assets/anatomy tree is ${mib(anatomyTree.bytes).toFixed(2)} MiB — ` +
          `also ≤ ${CAPS.glbMiB} MiB (strict reading)`,
      )
    : bad(
        `the whole src/assets/anatomy tree is ${mib(anatomyTree.bytes).toFixed(2)} MiB — ` +
          `above the ${CAPS.glbMiB} MiB cap under the strict reading`,
      )
}

console.log('\n── (3) imaging payload ' + '─'.repeat(56))
if (imagingTree === null) {
  bad('src/assets/imaging is missing — the imaging budget cannot be re-derived')
} else {
  info(`Σ stat(every file under src/assets/imaging) = ${home(imagingTree.bytes)} in ${imagingTree.files} file(s)`)
  mib(imagingTree.bytes) <= CAPS.imagingMiB
    ? ok(
        `imaging payload ${mib(imagingTree.bytes).toFixed(2)} MiB ≤ ${CAPS.imagingMiB} MiB ` +
          `(headroom ${(CAPS.imagingMiB - mib(imagingTree.bytes)).toFixed(2)} MiB)`,
      )
    : bad(
        `imaging payload ${mib(imagingTree.bytes).toFixed(2)} MiB EXCEEDS the ${CAPS.imagingMiB} MiB cap`,
      )
}

console.log('\n── tier boundary ' + '─'.repeat(60))
console.log('  This gate measures COMMITTED BYTES and the manifest arithmetic. It does not')
console.log('  re-bake geometry (that is `node scripts/build-anatomy-geometry.mjs --manifest`)')
console.log('  and it does not render: no browser is involved anywhere in this file.')

console.log('')
for (const line of checks) console.log(line)
for (const line of infos) console.log(line)
const failed = checks.filter((line) => line.startsWith('  ✗')).length
console.log(
  `\n${checks.length - failed} passed · ${failed} failed · ${infos.length} informational\n`,
)
if (failed > 0) {
  console.log('BUDGET BREACH — a hard constraint of the v7 run is violated.\n')
  process.exit(1)
}
console.log(
  `✔ budget report PASSED — ${num(tris)} tris · GLB ${mib(glbBytes).toFixed(2)} MiB · ` +
    `imaging ${imagingTree === null ? '?' : mib(imagingTree.bytes).toFixed(2)} MiB — all inside their caps\n`,
)
process.exit(0)
