/**
 * generated.ts — TypeScript types for src/assets/anatomy/anatomy-manifest.json
 * (REALISM_PLAN §4 manifest schema, verbatim; integration-v2 task).
 *
 * The manifest is machine-generated by scripts/build-anatomy-geometry.mjs
 * (per-part upsert on bake; `--manifest` regenerates the whole file from the
 * committed GLBs). Keep these types in lockstep with that schema — the runtime
 * loader (src/geometry/anatomyAssets.ts) types the JSON import through
 * AnatomyManifest, so a schema drift surfaces as a compile error.
 */
import type { Vec3 } from '../types'
import type { MaterialHint } from './materials'

/** How the part's surface was produced (REALISM_PLAN §1 layers). */
export type AnatomySource = 'bp3d+sculpt' | 'sculpt'

/** Part class: context envelopes, organic nuclei, and CSF spaces. */
export type AnatomyPartKind = 'context' | 'nucleus' | 'ventricle'

/** Canonical-space axis-aligned bounding box of the baked mesh. */
export interface AnatomyBbox {
  min: Vec3
  max: Vec3
}

/** One entry of anatomy-manifest.json `parts` (REALISM_PLAN §4 schema). */
export interface AnatomyPart {
  /** Slug — a ctx-/nuc-/vent- record id from src/data (1:1 with GLB). */
  slug: string
  /** GLB file name inside src/assets/anatomy/ (`${slug}.glb`). */
  file: string
  kind: AnatomyPartKind
  source: AnatomySource
  /** Preset for the central material factory (src/geometry/materials.ts). */
  materialHint: MaterialHint
  /** Triangle count of the committed GLB. */
  triCount: number
  /** Canonical-space centroid (explode offsets, QA). */
  centroid: Vec3
  bbox: AnatomyBbox
}

/** Root shape of src/assets/anatomy/anatomy-manifest.json. */
export interface AnatomyManifest {
  version: 2
  generatedBy: string
  parts: AnatomyPart[]
}
