/**
 * NeuroAxis SDF kernel — minimal Wavefront OBJ reader/writer.
 *
 * Scope (deliberately small, docs/GEOMETRY_PIPELINE.md):
 *  - parse: `v` (geometric vertices) and `f` faces only. Faces support the
 *    `v`, `v/vt`, `v/vt/vn` and `v//vn` token forms plus negative (relative)
 *    indices, and are fan-triangulated. All other lines (vn/vt/o/g/s/usemtl/
 *    mtllib/comments) are ignored. This is exactly enough for BodyParts3D
 *    exports and for canonical OBJ caches (scripts/lib/register.mjs output).
 *  - write: `v` + triangular `f` lines (1-based), nothing else.
 *
 * Plain Node ESM, zero dependencies.
 */

/**
 * Parse OBJ text.
 * @param {string} text
 * @returns {{
 *   positions: Float32Array,   // xyz triplets
 *   triangles: Uint32Array,    // vertex-index triplets (0-based)
 *   vertexCount: number,
 *   triangleCount: number
 * }}
 */
export function parseOBJ(text) {
  if (typeof text !== 'string') throw new Error('parseOBJ: text required');

  const vpos = []; // growing xyz list (plain array while parsing)
  const tris = [];
  let lineNo = 0;

  for (const rawLine of text.split('\n')) {
    lineNo += 1;
    const line = rawLine.trim();
    if (line.length === 0 || line.startsWith('#')) continue;

    if (line.startsWith('v ')) {
      const parts = line.slice(2).trim().split(/\s+/);
      if (parts.length < 3) throw new Error(`parseOBJ: line ${lineNo}: vertex needs 3 coordinates`);
      const x = Number(parts[0]), y = Number(parts[1]), z = Number(parts[2]);
      if (!Number.isFinite(x) || !Number.isFinite(y) || !Number.isFinite(z)) {
        throw new Error(`parseOBJ: line ${lineNo}: non-finite vertex`);
      }
      vpos.push(x, y, z);
      continue;
    }

    if (line.startsWith('f ')) {
      const tokens = line.slice(2).trim().split(/\s+/);
      if (tokens.length < 3) throw new Error(`parseOBJ: line ${lineNo}: face needs >= 3 vertices`);
      // Resolve each token to a 0-based vertex index (fan triangulation).
      const idx = tokens.map((tok) => {
        let s = tok.split('/')[0]; // drop vt/vn
        let n = Number(s);
        if (!Number.isInteger(n)) throw new Error(`parseOBJ: line ${lineNo}: bad face token "${tok}"`);
        if (n < 0) n = vpos.length / 3 + n; // relative indexing
        else n -= 1; // OBJ is 1-based
        if (n < 0 || n >= vpos.length / 3) {
          throw new Error(`parseOBJ: line ${lineNo}: face index out of range`);
        }
        return n;
      });
      for (let t = 1; t + 1 < idx.length; t += 1) {
        tris.push(idx[0], idx[t], idx[t + 1]);
      }
      continue;
    }
    // everything else ignored by contract
  }

  return {
    positions: Float32Array.from(vpos),
    triangles: Uint32Array.from(tris),
    vertexCount: vpos.length / 3,
    triangleCount: tris.length / 3,
  };
}

/**
 * Serialize a triangle mesh as minimal OBJ (`v` + `f` lines).
 * @param {object} mesh
 * @param {Array|Float32Array} mesh.positions  xyz triplets
 * @param {Array|Uint32Array} [mesh.triangles]  0-based index triplets; when
 *   omitted, positions are emitted as an indexed-by-order point soup is NOT
 *   written — omitting triangles writes vertices only.
 * @param {object} [opts] { name?: string, comment?: string, precision = 6 }
 * @returns {string}
 */
export function writeOBJ(mesh, opts = {}) {
  if (!mesh || !mesh.positions) throw new Error('writeOBJ: mesh.positions required');
  const precision = opts.precision ?? 6;
  const out = [];
  out.push(`# Generated by scripts/lib/sdf/objio.js (NeuroAxis SDF kernel)`);
  if (opts.comment) out.push(`# ${String(opts.comment).replace(/\n/g, ' ')}`);
  if (opts.name) out.push(`o ${opts.name}`);

  const p = mesh.positions;
  for (let i = 0; i < p.length; i += 3) {
    out.push(`v ${p[i].toFixed(precision)} ${p[i + 1].toFixed(precision)} ${p[i + 2].toFixed(precision)}`);
  }
  const t = mesh.triangles;
  if (t) {
    for (let i = 0; i < t.length; i += 3) {
      out.push(`f ${t[i] + 1} ${t[i + 1] + 1} ${t[i + 2] + 1}`);
    }
  }
  out.push('');
  return out.join('\n');
}
